### ISSUE TITLE
你好 请求你httpclient插件中为什么要对请求的流进行了复制？

### ISSUE THREAD

**Issue by afeiiiii** [vivo/jvm-sandbox-repeater#2]
https://github.com/vivo/jvm-sandbox-repeater/blob/f1d850e4bf3253bf5ff38f8c7d488471b27736bc/repeater-plugins/apache-http-client-plugin/src/main/java/com/alibaba/jvm/sandbox/repeater/plugin/apachehttpclient/ApacheHttpClientProcessor.java#L285

**Comment by yananliuyanjiang** [comment]
这是因为原生 http request请求流只能读取一次，读取完后后续业务代码就没办法在读取，因此在这里对请求流进行复制读取，保证不影响原有InputStram流读取。

**Comment by lemon-simple** [comment]
@afeiiiii 后续我们预计会推动 一个独立的 流量录制回放产品 开源，用户可以直接一站式使用，欢迎关注与参与。有兴趣参与可以加我微信号：zsyounginsummer
